0 REM ---------------------
1 REM WeakPoint V.1.0
2 REM Tisnik 2013, 2022
3 REM ---------------------
4 PRINT ""
5 PRINT "WeakPoint V.1.0"
6 PRINT "Tisnik 2013, 2022"
7 PRINT "*********************"
8 PRINT ""
9 GOSUB 10000
10 PRINT "SLIDE: ";SLIDE
11 PRINT " PREVIOUS SLIDE"
12 PRINT " NEXT SLIDE"
20 GOSUB KEYCODE
30 KEY=PEEK(754)
40 SLIDE=SLIDE-(KEY=LEFTKEY)
41 SLIDE=SLIDE+(KEY=RIGHTKEY)
50 IF SLIDE>0 THEN GOSUB SLIDE*100
60 GOTO MAINLOOP
100 REM slide # 0
101 GRAPHICS 2

## NES

* Nintendo
* Entertainment
* System

200 REM slide # 1
201 GRAPHICS 2

## game console

* 62 millions sold
* about 50 compatible clones
* various plugins
* MIDI
* floppy disk
* modem

300 REM slide # 2
301 GRAPHICS 2

## Overview

* cpu
* memory
* graphics
* sound
* controllers
* copy protection

400 REM slide # 3
401 GRAPHICS 2

## RICOH 2A03/2A07

* ricoh 2a03 cpu
* nes/gameboy

* 2a03 - ntsc
* 2a07 - pal

* 1,66 MHz PAL
* 1,79 MHz NTSC

500 REM slide # 4
501 GRAPHICS 2

## RICOH 2A03/2A07

* based on mos 6502

* 2a03 vs mos 6502
* - ÂÃÄ ÍÏÄÅ
* + ÔÉÍÅÒ
* + ÄÍÁ
* + ÓÏÕÎÄ ÓÙÓÔÅÍ

600 REM slide # 5
601 GRAPHICS 2

## MEMORY

* two memory chips
* program+data RAM
* graphics data
* no built-in ROM
* EPROM on cartridge

700 REM slide # 6
701 GRAPHICS 2

## GRAPHICS

* generated by PPU
* RP2C02/RP2C07
* a bit complicated
* (multiple tables)

800 REM slide # 7
801 GRAPHICS 2

## GRAPHICS

* 256B sprite RAM
* 2KB background RAM
* and ROM on cartridge

900 REM slide # 8
901 GRAPHICS 2

## SOUND

* generated by cpu
* 2A03/2A07

1000 REM slide # 9
1001 GRAPHICS 2

## 2A03 SOUND SYSTEM

* 5 channels
* 2 square waves
* 1 triangle wave
* 1 noise generator
* 1 d/a converter

* 22 control registers

1100 REM slide # 10
1101 GRAPHICS 2

## 2A03 SQUARE WAVES

* 54.6 hz - 12,4 khz
* 4 bit amplitude
* variable duty
* 1:8
* 1:4
* 1:2
* 3:4

1200 REM slide # 11
1201 GRAPHICS 2

## 2A03 TRIANGLE WAVE

* 27.3 hz - 55.9 khz
* 4 bit amplitude
* (automatic control)

1300 REM slide # 12
1301 GRAPHICS 2

## 2A03 NOISE GENERATOR

* 15 bit lfsr
* 29.3 hz - 447 khz
* two modes
* ÌÏÎÇ
* 32767 âéô ãùãìå
* ÓÈÏÒÔ
* 93 âéô ãùãìå

1400 REM slide # 13
1401 GRAPHICS 2

## 2A03 D/A CONVERTER

* dmc
* ÄÅÌÔÁ ÍÏÄÕÌÁÔÉÏÎ

* 7 bit
* 4.2 khz - 33.5 khz
* semi automatic dma
* non-linear d/a
10000 REM
10001 REM ---------------------
10002 REM INICIALIZACE
10003 REM ---------------------
10010 SLIDE=0
10020 MAINLOOP=10
10030 KEYCODE=10100
10031 LEFTKEY=134
10032 RIGHTKEY=135
10090 RETURN
10100 REM
10101 REM ---------------------
10102 REM PRECTENI KLAVESY
10103 REM ---------------------
10110 POKE 754,255
10120 IF PEEK(754)=255 THEN 10120
10130 RETURN
20000 REM
20001 REM ---------------------
20002 REM LOAD RUTINA
20003 REM ---------------------
20010 GRAPHICS 8
20020 ADDR=PEEK(88)+256*PEEK(89)
20030 OPEN #1,4,0,"H:IMAGE.PBM"
20040 FOR I=0 TO 6400-1
20050 GET #1,A
20060 POKE ADDR,A
20070 ADDR=ADDR+1
20080 NEXT I
20090 CLOSE #1
20100 RETURN
