0 REM ---------------------
1 REM WeakPoint V.1.0
2 REM Tisnik 2013, 2022
3 REM ---------------------
4 PRINT ""
5 PRINT "WeakPoint V.1.0"
6 PRINT "Tisnik 2013, 2022"
7 PRINT "*********************"
8 PRINT ""
9 GOSUB 10000
10 PRINT "SLIDE: ";SLIDE
11 PRINT " PREVIOUS SLIDE"
12 PRINT " NEXT SLIDE"
20 GOSUB KEYCODE
30 KEY=PEEK(754)
40 SLIDE=SLIDE-(KEY=LEFTKEY)
41 SLIDE=SLIDE+(KEY=RIGHTKEY)
50 IF SLIDE>0 THEN GOSUB SLIDE*100
60 GOTO MAINLOOP
100 REM slide # 0
101 GRAPHICS 2
102 ? #6;""
103 ? #6;"нес"
104 ? #6;""
105 ? #6;"* Nintendo"
106 ? #6;"* Entertainment"
107 ? #6;"* System"
108 ? #6;""
109 RETURN
200 REM slide # 1
201 GRAPHICS 2
202 ? #6;""
203 ? #6;"гаме═цонсоле"
204 ? #6;""
205 ? #6;"* 62 millions sold"
206 ? #6;"* about 50 clones"
207 ? #6;"* various plugins"
208 ? #6;"- midi"
209 ? #6;"- floppy disk"
210 ? #6;"- modem"
211 ? #6;""
212 RETURN
300 REM slide # 2
301 GRAPHICS 2
302 ? #6;""
303 ? #6;"ожержиев"
304 ? #6;""
305 ? #6;"* cpu"
306 ? #6;"* memory"
307 ? #6;"* graphics"
308 ? #6;"* sound"
309 ? #6;"* controllers"
310 ? #6;"* copy protection"
311 ? #6;""
312 RETURN
400 REM slide # 3
401 GRAPHICS 2
402 ? #6;""
403 ? #6;"рицох═╡а╟Ё╞╡а╟╥"
404 ? #6;""
405 ? #6;"* ricoh 2a03 cpu"
406 ? #6;""
407 ? #6;"* 2a03 - ntsc"
408 ? #6;"* 2a07 - pal"
409 ? #6;""
410 ? #6;"* 1,66 MHz PAL"
411 ? #6;"* 1,79 MHz NTSC"
412 ? #6;""
413 RETURN
500 REM slide # 4
501 GRAPHICS 2
502 ? #6;""
503 ? #6;"рицох═╡а╟Ё╞╡а╟╥"
504 ? #6;""
505 ? #6;"* based on mos 6502"
506 ? #6;""
507 ? #6;"* 2a03 vs mos 6502"
508 ? #6;"- - bcd mode"
509 ? #6;"- + timer"
510 ? #6;"- + dma"
511 ? #6;"- + sound system"
512 ? #6;""
513 RETURN
600 REM slide # 5
601 GRAPHICS 2
602 ? #6;""
603 ? #6;"меморы"
604 ? #6;""
605 ? #6;"* two memory chips"
606 ? #6;"- program+data"
607 ? #6;"- graphics data"
608 ? #6;"* no built-in ROM"
609 ? #6;"* EPROM on cartridge"
610 ? #6;""
611 RETURN
700 REM slide # 6
701 GRAPHICS 2
702 ? #6;""
703 ? #6;"грапхицс"
704 ? #6;""
705 ? #6;"* generated by PPU"
706 ? #6;"* 256x240 pixels"
707 ? #6;"* RP2C02/RP2C07"
708 ? #6;"* a bit complicated"
709 ? #6;"- multiple tables"
710 ? #6;""
711 RETURN
800 REM slide # 7
801 GRAPHICS 2
802 ? #6;""
803 ? #6;"грапхицс"
804 ? #6;""
805 ? #6;"* 256B sprite RAM"
806 ? #6;"* 2KB background RAM"
807 ? #6;"* and ROM on cartridge"
808 ? #6;"* 64 color system pal."
809 ? #6;""
810 ? #6;"* as few CPU cycles"
811 ? #6;"as possible"
812 ? #6;""
813 RETURN
900 REM slide # 8
901 GRAPHICS 2
902 ? #6;""
903 ? #6;"бацкгроунд═ё╠"
904 ? #6;""
905 ? #6;"* 256x240 pixels"
906 ? #6;"- not bitmap"
907 ? #6;"- tiles 8x8"
908 ? #6;"- groups 4x4 t"
909 ? #6;"- 4 palettes"
910 ? #6;"- 4 colors each"
911 ? #6;"- 3 unique"
912 ? #6;"- 1 shared"
913 ? #6;""
914 RETURN
1000 REM slide # 9
1001 GRAPHICS 2
1002 ? #6;""
1003 ? #6;"бацкгроунд═ё╡"
1004 ? #6;""
1005 ? #6;"* PATTERN TABLE"
1006 ? #6;"- in ROM"
1007 ? #6;"- tiles 8x8"
1008 ? #6;"- 2 bpp"
1009 ? #6;"* size"
1010 ? #6;"- 16 bytes"
1011 ? #6;"per tile"
1012 ? #6;"* 256 tiles"
1013 ? #6;"= 4096 bytes"
1014 ? #6;""
1015 RETURN
1100 REM slide # 10
1101 GRAPHICS 2
1102 ? #6;""
1103 ? #6;"бацкгроунд═ёЁ"
1104 ? #6;""
1105 ? #6;"* ATTRIBUTE TABLE"
1106 ? #6;"- 64 (60) bytes"
1107 ? #6;"- upper 2 bits"
1108 ? #6;"- for 4x4 tiles"
1109 ? #6;"- 32x32 pixels"
1110 ? #6;"* why?"
1111 ? #6;"- tiles 2bpp"
1112 ? #6;"-> palette #"
1113 ? #6;"- attrib. 2bpp"
1114 ? #6;"-> color from"
1115 ? #6;"palette"
1116 RETURN
1200 REM slide # 11
1201 GRAPHICS 2
1202 ? #6;""
1203 ? #6;"бацкгроунд═ё╢"
1204 ? #6;""
1205 ? #6;"* NAME TABLE"
1206 ? #6;"- in RAM"
1207 ? #6;"- grid 32x30"
1208 ? #6;"- offsets"
1209 ? #6;"- 960 bytes"
1210 ? #6;"* can be manipulated"
1211 ? #6;"quickly"
1212 ? #6;""
1213 RETURN
1300 REM slide # 12
1301 GRAPHICS 2
1302 ? #6;""
1303 ? #6;"бацкгроунд═ё╣"
1304 ? #6;""
1305 ? #6;"* PPU rendering:"
1306 ? #6;"- read tile #"
1307 ? #6;"from NAME TABLE"
1308 ? #6;"- read palette #"
1309 ? #6;"from ATTRIB.T."
1310 ? #6;"- read pixel"
1311 ? #6;"colors from"
1312 ? #6;"PATTERN TABLE"
1313 ? #6;"* without CPU ^"
1314 ? #6;""
1315 RETURN
1400 REM slide # 13
1401 GRAPHICS 2
1402 ? #6;""
1403 ? #6;"спритес═ё╠"
1404 ? #6;""
1405 ? #6;"* PATTERN TABLE"
1406 ? #6;"- in ROM"
1407 ? #6;"- tiles 8x8"
1408 ? #6;"- 2 bpp"
1409 ? #6;"* SPRITE RAM"
1410 ? #6;"- 256 bytes"
1411 ? #6;""
1412 RETURN
1500 REM slide # 14
1501 GRAPHICS 2
1502 ? #6;""
1503 ? #6;"спритес═ёЁ"
1504 ? #6;""
1505 ? #6;"* SPRITE RAM"
1506 ? #6;"* 64 sprites"
1507 ? #6;"* 4 bytes/sprite"
1508 ? #6;"- tile #"
1509 ? #6;"- x-position"
1510 ? #6;"- y-position"
1511 ? #6;"- attributes"
1512 ? #6;""
1513 RETURN
1600 REM slide # 15
1601 GRAPHICS 2
1602 ? #6;""
1603 ? #6;"спритес═ё╢"
1604 ? #6;""
1605 ? #6;"* attribues"
1606 ? #6;"- palette 4-7"
1607 ? #6;"- priority"
1608 ? #6;"- flip hor."
1609 ? #6;"- flip ver."
1610 ? #6;""
1611 RETURN
1700 REM slide # 16
1701 GRAPHICS 2
1702 ? #6;""
1703 ? #6;"цолорс"
1704 ? #6;""
1705 ? #6;"* background"
1706 ? #6;"- main bg.color"
1707 ? #6;"- 4 palettes"
1708 ? #6;"- each 3 colors"
1709 ? #6;"- 13 in overall"
1710 ? #6;"* sprites"
1711 ? #6;"- 4 palettes"
1712 ? #6;"- each 3 colors"
1713 ? #6;"- 12 in overall"
1714 ? #6;"* sum"
1715 ? #6;"- 25 colors on"
1716 ? #6;"screen w/o any"
1717 ? #6;"tricks"
1718 ? #6;""
1719 RETURN
1800 REM slide # 17
1801 GRAPHICS 2
1802 ? #6;""
1803 ? #6;"соунд"
1804 ? #6;""
1805 ? #6;"* generated by cpu"
1806 ? #6;"* 2A03/2A07"
1807 ? #6;""
1808 RETURN
1900 REM slide # 18
1901 GRAPHICS 2
1902 ? #6;""
1903 ? #6;"╡а╟Ё═соунд═сыстем"
1904 ? #6;""
1905 ? #6;"* 5 channels"
1906 ? #6;"* 2 square waves"
1907 ? #6;"* 1 triangle wave"
1908 ? #6;"* 1 noise generator"
1909 ? #6;"* 1 d/a converter"
1910 ? #6;""
1911 ? #6;"* 22 control registers"
1912 ? #6;""
1913 RETURN
2000 REM slide # 19
2001 GRAPHICS 2
2002 ? #6;""
2003 ? #6;"╡а╟Ё═сяуаре═важес"
2004 ? #6;""
2005 ? #6;"* 54.6 hz - 12,4 khz"
2006 ? #6;"* 4 bit amplitude"
2007 ? #6;"* variable duty"
2008 ? #6;"* 1:8"
2009 ? #6;"* 1:4"
2010 ? #6;"* 1:2"
2011 ? #6;"* 3:4"
2012 ? #6;""
2013 RETURN
2100 REM slide # 20
2101 GRAPHICS 2
2102 ? #6;""
2103 ? #6;"╡а╟Ё═триангле═важе"
2104 ? #6;""
2105 ? #6;"* 27.3 hz - 55.9 khz"
2106 ? #6;"* 4 bit amplitude"
2107 ? #6;"* (automatic control)"
2108 ? #6;""
2109 RETURN
2200 REM slide # 21
2201 GRAPHICS 2
2202 ? #6;""
2203 ? #6;"╡а╟Ё═ноисе═генератор"
2204 ? #6;""
2205 ? #6;"* 15 bit lfsr"
2206 ? #6;"* 29.3 hz - 447 khz"
2207 ? #6;"* two modes"
2208 ? #6;"* long"
2209 ? #6;"*   32767 bit cycle"
2210 ? #6;"* short"
2211 ? #6;"*   93 bit cycle"
2212 RETURN
2300 REM slide # 22
2301 GRAPHICS 2
2302 ? #6;""
2303 ? #6;"╡а╟Ё═д╞а═цонжертер"
2304 ? #6;""
2305 ? #6;"* dmc"
2306 ? #6;"- delta modulation"
2307 ? #6;"* 7 bit"
2308 ? #6;"* 4.2 khz - 33.5 khz"
2309 ? #6;"* semi automatic dma"
2310 ? #6;"* non-linear d/a"
2311 ? #6;""
2312 RETURN
2400 REM slide # 23
2401 GRAPHICS 2
2402 ? #6;""
2403 ? #6;"цонтроллерс"
10000 REM 
10001 REM ---------------------
10002 REM INICIALIZACE
10003 REM ---------------------
10010 SLIDE=0
10020 MAINLOOP=10
10030 KEYCODE=10100
10031 LEFTKEY=134
10032 RIGHTKEY=135
10090 RETURN 
10100 REM 
10101 REM ---------------------
10102 REM PRECTENI KLAVESY
10103 REM ---------------------
10110 POKE 754,255
10120 IF PEEK(754)=255 THEN 10120
10130 RETURN 
20000 REM 
20001 REM ---------------------
20002 REM LOAD RUTINA
20003 REM ---------------------
20010 GRAPHICS 8
20020 ADDR=PEEK(88)+256*PEEK(89)
20030 OPEN #1,4,0,"H:IMAGE.PBM"
20040 FOR I=0 TO 6400-1
20050 GET #1,A
20060 POKE ADDR,A
20070 ADDR=ADDR+1
20080 NEXT I
20090 CLOSE #1
20100 RETURN 
