;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_bank_spr
	.import		_bank_bg
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_fill
	.export		_i
	.export		_address
	.export		_background_palette
	.export		_sprite_palette
	.export		_metasprite
	.export		_fill_in_ppu_ram
	.export		_fill_in_attributes
	.export		_game_loop
	.export		_main

.segment	"RODATA"

_background_palette:
	.byte	$22
	.byte	$29
	.byte	$1A
	.byte	$0F
	.byte	$22
	.byte	$36
	.byte	$17
	.byte	$0F
	.byte	$22
	.byte	$30
	.byte	$21
	.byte	$0F
	.byte	$22
	.byte	$27
	.byte	$17
	.byte	$0F
_sprite_palette:
	.byte	$22
	.byte	$16
	.byte	$27
	.byte	$18
	.byte	$22
	.byte	$1A
	.byte	$30
	.byte	$27
	.byte	$22
	.byte	$16
	.byte	$30
	.byte	$27
	.byte	$22
	.byte	$0F
	.byte	$36
	.byte	$17
_metasprite:
	.byte	$0A
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$0A
	.byte	$01
	.byte	$00
	.byte	$0A
	.byte	$12
	.byte	$02
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$03
	.byte	$00
	.byte	$0A
	.byte	$14
	.byte	$04
	.byte	$00
	.byte	$12
	.byte	$14
	.byte	$05
	.byte	$00
	.byte	$0A
	.byte	$1C
	.byte	$06
	.byte	$00
	.byte	$12
	.byte	$1C
	.byte	$07
	.byte	$00
	.byte	$80

.segment	"BSS"

.segment	"ZEROPAGE"
_i:
	.res	2,$00
_address:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ fill_in_ppu_ram (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_in_ppu_ram: near

.segment	"CODE"

;
; vram_adr(NTADR_A(0, 0));
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (i = 0; i < 32 * 30; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L004B:	lda     _i
	cmp     #$C0
	lda     _i+1
	sbc     #$03
	bvc     L0052
	eor     #$80
L0052:	bpl     L004C
;
; vram_put(36);
;
	lda     #$24
	jsr     _vram_put
;
; for (i = 0; i < 32 * 30; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0054
	inx
L0054:	sta     _i
	stx     _i+1
	jmp     L004B
;
; }
;
L004C:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fill_in_attributes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_in_attributes: near

.segment	"CODE"

;
; vram_adr(ATTRIBUTE_TABLE);
;
	ldx     #$23
	lda     #$C0
	jsr     _vram_adr
;
; vram_fill(0, 16);
;
	lda     #$00
	jsr     pusha
	tax
	lda     #$10
	jsr     _vram_fill
;
; vram_fill(0x55, 16);
;
	lda     #$55
	jsr     pusha
	ldx     #$00
	lda     #$10
	jsr     _vram_fill
;
; vram_fill(0xAA, 16);
;
	lda     #$AA
	jsr     pusha
	ldx     #$00
	lda     #$10
	jsr     _vram_fill
;
; vram_fill(0xFF, 16);
;
	lda     #$FF
	jsr     pusha
	ldx     #$00
	lda     #$10
	jmp     _vram_fill

.endproc

; ---------------------------------------------------------------
; void __near__ game_loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_loop: near

.segment	"CODE"

;
; ppu_wait_nmi();
;
L0067:	jsr     _ppu_wait_nmi
;
; oam_clear();
;
	jsr     _oam_clear
;
; oam_meta_spr(10, 10, metasprite);
;
	jsr     decsp2
	lda     #$0A
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_metasprite)
	ldx     #>(_metasprite)
	jsr     _oam_meta_spr
;
; while (1) {
;
	jmp     L0067

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; pal_bg(background_palette);
;
	lda     #<(_background_palette)
	ldx     #>(_background_palette)
	jsr     _pal_bg
;
; pal_spr(sprite_palette);
;
	lda     #<(_sprite_palette)
	ldx     #>(_sprite_palette)
	jsr     _pal_spr
;
; bank_bg(1);
;
	lda     #$01
	jsr     _bank_bg
;
; bank_spr(0);
;
	lda     #$00
	jsr     _bank_spr
;
; fill_in_ppu_ram();
;
	jsr     _fill_in_ppu_ram
;
; fill_in_attributes();
;
	jsr     _fill_in_attributes
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; game_loop();
;
	jmp     _game_loop

.endproc

