;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; register unsigned char a;
;
	lda     regbank+5
	jsr     pusha
;
; register unsigned char b;
;
	lda     regbank+4
	jsr     pusha
;
; register unsigned char c;
;
	lda     regbank+3
	jsr     pusha
;
; __asm__ ("lda %v", a);
;
	lda     regbank+5
;
; __asm__ ("clc");
;
	clc
;
; __asm__ ("adc %v", b);
;
	adc     regbank+4
;
; __asm__ ("sta %v", c);
;
	sta     regbank+3
;
; }
;
	ldy     #$00
L000A:	lda     (sp),y
	sta     regbank+3,y
	iny
	cpy     #$03
	bne     L000A
	jmp     incsp3

.endproc

