;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; register unsigned char a;
;
	lda     regbank+5
	jsr     pusha
;
; __asm__ ("lda #1");
;
	lda     #1
;
; __asm__ ("clc");
;
	clc
;
; __asm__ ("adc #2");
;
	adc     #2
;
; __asm__ ("sta %v", a);
;
	sta     regbank+5
;
; }
;
	ldy     #$00
	lda     (sp),y
	sta     regbank+5
	jmp     incsp1

.endproc

