;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_a
	.export		_b
	.export		_c
	.export		_main

.segment	"BSS"

_a:
	.res	1,$00
_b:
	.res	1,$00
_c:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; __asm__ ("lda %v", a);
;
	lda     _a
;
; __asm__ ("clc");
;
	clc
;
; __asm__ ("adc %v", b);
;
	adc     _b
;
; __asm__ ("sta %v", c);
;
	sta     _c
;
; }
;
	rts

.endproc

