;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_memset8
	.export		_main

; ---------------------------------------------------------------
; void __near__ memset8 (__near__ unsigned char *, const unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_memset8: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; *dest++ = c;
;
L0002:	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	ldy     #$01
	lda     (sp),y
	dey
	sta     (regsave),y
;
; n--;
;
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
;
; } while (n > 0);
;
	lda     (sp),y
	bne     L0002
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L000A:
	.res	2,$00
L000C:
	.res	1,$00
L000E:
	.res	1,$00

.segment	"CODE"

;
; uint8_t *dest = (uint8_t *) 0x0600;
;
	ldx     #$06
	lda     #$00
	sta     L000A
	stx     L000A+1
;
; uint8_t bytes = 0xff;
;
	lda     #$FF
	sta     L000C
;
; uint8_t fill = 0x00;
;
	lda     #$00
	sta     L000E
;
; memset8(dest, fill, bytes);
;
	lda     L000A
	ldx     L000A+1
	jsr     pushax
	lda     L000E
	jsr     pusha
	lda     L000C
	jsr     _memset8
;
; return 0;
;
	ldx     #$00
	txa
;
; }
;
	rts

.endproc

