;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_memset8
	.export		_main

; ---------------------------------------------------------------
; void __near__ memset8 (__near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_memset8: near

.segment	"BSS"

L0002:
	.res	2,$00

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; for (i = 0; i < n; i++) {
;
	lda     #$00
	sta     L0002
	sta     L0002+1
L0003:	lda     L0002
	ldy     #$00
	cmp     (sp),y
	lda     L0002+1
	sbc     #$00
	bcs     L0004
;
; dest[i] = c;
;
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     L0002
	sta     ptr1
	txa
	adc     L0002+1
	sta     ptr1+1
	ldy     #$01
	lda     (sp),y
	dey
	sta     (ptr1),y
;
; for (i = 0; i < n; i++) {
;
	lda     L0002
	ldx     L0002+1
	jsr     incax1
	sta     L0002
	stx     L0002+1
	jmp     L0003
;
; }
;
L0004:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L000F:
	.res	2,$00
L0011:
	.res	1,$00
L0013:
	.res	1,$00

.segment	"CODE"

;
; uint8_t *dest = (uint8_t *) 0x0600;
;
	ldx     #$06
	lda     #$00
	sta     L000F
	stx     L000F+1
;
; uint8_t bytes = 0xff;
;
	lda     #$FF
	sta     L0011
;
; uint8_t fill = 0x00;
;
	lda     #$00
	sta     L0013
;
; memset8(dest, fill, bytes);
;
	lda     L000F
	ldx     L000F+1
	jsr     pushax
	lda     L0013
	jsr     pusha
	lda     L0011
	jsr     _memset8
;
; return 0;
;
	ldx     #$00
	txa
;
; }
;
	rts

.endproc

