;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
        .fopt           compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
        .setcpu         "6502"
        .smart          on
        .autoimport     on
        .case           on
        .debuginfo      off
        .importzp       sp, sreg, regsave, regbank
        .importzp       tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
        .macpack        longbranch
        .forceimport    __STARTUP__
        .export         _main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _main: near

.segment        "BSS"

L0002:
        .res    2,$00

.segment        "CODE"

;
; register unsigned int x = 42;
;
        ldx     #$00
        lda     #$2A
        sta     L0002
        stx     L0002+1
;
; ++x;
;
        inc     L0002
        bne     L0005
        inc     L0002+1
;
; }
;
L0005:  rts

.endproc

