package main

import (
	"bytes"
	"fmt"
	"io"
	"time"
)

const (
	transpilerName = "Goto BASIC"
	majorVersion   = 0
	minorVersion   = 1
)

func GenerateBasicSource(writer io.Writer, timestamp time.Time, sourceFile string) {
	fmt.Fprintf(writer, "10 REM Source file:  %s\n", sourceFile)
	todayFmt := timestamp.Format("2006-01-02 15:04:05 MST")
	fmt.Fprintf(writer, "11 REM Generated at: %s\n", todayFmt)
	fmt.Fprintf(writer, "12 REM Generated by: %s v%d.%d\n", transpilerName, majorVersion, minorVersion)
}

func main() {
	var buffer bytes.Buffer

	GenerateBasicSource(&buffer, time.Now(), "test.go")

	fmt.Println(buffer.String())
}
