[tool.ruff]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["E", "F", "W", "C", "D"]
select = ["E", "F", "W", "C"]
ignore = []

line-length = 100

