;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_bank_bg
	.import		_vram_adr
	.import		_vram_put
	.export		_i
	.export		_address
	.export		_palette
	.export		_nametable
	.export		_attributes
	.export		_fill_in_ppu_ram
	.export		_fill_in_attributes
	.export		_game_loop
	.export		_main

.segment	"RODATA"

_palette:
	.byte	$22
	.byte	$29
	.byte	$1A
	.byte	$0F
	.byte	$22
	.byte	$36
	.byte	$17
	.byte	$0F
	.byte	$22
	.byte	$30
	.byte	$21
	.byte	$0F
	.byte	$22
	.byte	$27
	.byte	$17
	.byte	$0F
	.byte	$22
	.byte	$16
	.byte	$27
	.byte	$18
	.byte	$22
	.byte	$1A
	.byte	$30
	.byte	$27
	.byte	$22
	.byte	$16
	.byte	$30
	.byte	$27
	.byte	$22
	.byte	$0F
	.byte	$36
	.byte	$17
_nametable:
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$D0
	.byte	$E8
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$DE
	.byte	$D1
	.byte	$D8
	.byte	$D0
	.byte	$D1
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DE
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$42
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$42
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DE
	.byte	$DF
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DE
	.byte	$DF
	.byte	$DB
	.byte	$DB
	.byte	$E4
	.byte	$E5
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DE
	.byte	$43
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$E6
	.byte	$E3
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$D4
	.byte	$D9
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$DB
	.byte	$D4
	.byte	$D9
	.byte	$D4
	.byte	$D9
	.byte	$E7
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$97
	.byte	$98
	.byte	$78
	.byte	$78
	.byte	$78
	.byte	$95
	.byte	$95
	.byte	$97
	.byte	$98
	.byte	$97
	.byte	$98
	.byte	$95
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$D0
	.byte	$E8
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$DE
	.byte	$D1
	.byte	$D8
	.byte	$D0
	.byte	$D1
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DE
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$D0
	.byte	$D1
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$42
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$42
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$42
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DE
	.byte	$DF
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DE
	.byte	$DF
	.byte	$DB
	.byte	$DB
	.byte	$E4
	.byte	$E5
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DE
	.byte	$43
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$E6
	.byte	$E3
	.byte	$26
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$42
	.byte	$DB
	.byte	$DB
	.byte	$DB
	.byte	$D4
	.byte	$D9
	.byte	$26
	.byte	$29
	.byte	$29
	.byte	$DB
	.byte	$DB
	.byte	$D4
	.byte	$D9
	.byte	$D4
	.byte	$D9
	.byte	$E7
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$97
	.byte	$98
	.byte	$78
	.byte	$78
	.byte	$78
	.byte	$95
	.byte	$95
	.byte	$97
	.byte	$98
	.byte	$97
	.byte	$98
	.byte	$95
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$1B
	.byte	$18
	.byte	$18
	.byte	$1D
	.byte	$24
	.byte	$25
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A5
	.byte	$A6
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A5
	.byte	$A6
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$53
	.byte	$54
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A7
	.byte	$A8
	.byte	$24
	.byte	$45
	.byte	$45
	.byte	$24
	.byte	$24
	.byte	$45
	.byte	$45
	.byte	$45
	.byte	$45
	.byte	$53
	.byte	$54
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A7
	.byte	$A8
	.byte	$47
	.byte	$47
	.byte	$24
	.byte	$24
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$55
	.byte	$56
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$55
	.byte	$56
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A5
	.byte	$A6
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A5
	.byte	$A6
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$53
	.byte	$54
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A7
	.byte	$A8
	.byte	$24
	.byte	$45
	.byte	$45
	.byte	$24
	.byte	$24
	.byte	$45
	.byte	$45
	.byte	$45
	.byte	$45
	.byte	$53
	.byte	$54
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$A7
	.byte	$A8
	.byte	$47
	.byte	$47
	.byte	$24
	.byte	$24
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$55
	.byte	$56
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$55
	.byte	$56
	.byte	$24
	.byte	$24
_attributes:
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$BF
	.byte	$FF
	.byte	$AA
	.byte	$FF
	.byte	$AA
	.byte	$55
	.byte	$AA
	.byte	$55
	.byte	$EF
	.byte	$FF
	.byte	$55
	.byte	$FF
	.byte	$55
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"BSS"

.segment	"ZEROPAGE"
_i:
	.res	2,$00
_address:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ fill_in_ppu_ram (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_in_ppu_ram: near

.segment	"CODE"

;
; vram_adr(NTADR_A(0, 0));
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (i = 0; i < 32 * 24; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L036C:	lda     _i
	cmp     #$00
	lda     _i+1
	sbc     #$03
	bvc     L0373
	eor     #$80
L0373:	asl     a
	lda     #$00
	bcc     L03A5
;
; vram_put(nametable[i]);
;
	lda     #<(_nametable)
	sta     ptr1
	lda     #>(_nametable)
	clc
	adc     _i+1
	sta     ptr1+1
	ldy     _i
	lda     (ptr1),y
	jsr     _vram_put
;
; for (i = 0; i < 32 * 24; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0375
	inx
L0375:	sta     _i
	stx     _i+1
	jmp     L036C
;
; for (i = 0; i < 32 * 6; i++) {
;
L03A5:	sta     _i
	sta     _i+1
L0379:	lda     _i
	cmp     #$C0
	lda     _i+1
	sbc     #$00
	bvc     L0380
	eor     #$80
L0380:	bpl     L037A
;
; vram_put(0x24);
;
	lda     #$24
	jsr     _vram_put
;
; for (i = 0; i < 32 * 6; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0382
	inx
L0382:	sta     _i
	stx     _i+1
	jmp     L0379
;
; }
;
L037A:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fill_in_attributes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_in_attributes: near

.segment	"CODE"

;
; vram_adr(ATTRIBUTE_TABLE);
;
	ldx     #$23
	lda     #$C0
	jsr     _vram_adr
;
; for (i = 0; i < 8 * 8; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L0388:	lda     _i
	cmp     #$40
	lda     _i+1
	sbc     #$00
	bvc     L038F
	eor     #$80
L038F:	bpl     L0389
;
; vram_put(attributes[i]);
;
	lda     #<(_attributes)
	sta     ptr1
	lda     #>(_attributes)
	clc
	adc     _i+1
	sta     ptr1+1
	ldy     _i
	lda     (ptr1),y
	jsr     _vram_put
;
; for (i = 0; i < 8 * 8; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0391
	inx
L0391:	sta     _i
	stx     _i+1
	jmp     L0388
;
; }
;
L0389:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_loop: near

.segment	"CODE"

;
; while (1) {
;
L03A6:	jmp     L03A6

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; pal_bg(palette);
;
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; bank_bg(1);
;
	lda     #$01
	jsr     _bank_bg
;
; fill_in_ppu_ram();
;
	jsr     _fill_in_ppu_ram
;
; fill_in_attributes();
;
	jsr     _fill_in_attributes
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; game_loop();
;
	jmp     _game_loop

.endproc

