ASSEMBLER := pasmo

all: 01.tap 02.tap 03.tap 04.tap 05.tap 06.tap 07.tap 08.tap 09.tap 10.tap \
    11.tap 12.tap 13.tap 14.tap 15.tap 16.tap 17.tap 18.tap 19.tap 20.tap \
    21.tap 22.tap 23.tap 24.tap 25.tap 26.tap 27.tap 28.tap 29.tap 30.tap \
    31.tap 32.tap 33.tap 34.tap 35.tap 36.tap 37.tap 38.tap 39.tap 40.tap \
    41.tap 42.tap 43.tap 44.tap 45.tap 46.tap 47.tap 48.tap 49.tap 50.tap \
    51.tap 52.tap 53.tap 54.tap 55.tap 56.tap 57.tap 58.tap 59.tap 60.tap \
    61.tap 62.tap 63.tap 64.tap 65.tap 66.tap 67.tap 68.tap 69.tap 70.tap \
    71.tap 72.tap 73.tap 74.tap 75.tap 76.tap 77.tap 78.tap 79.tap 80.tap \
    81.tap 82.tap 83.tap 84.tap 85.tap 86.tap 87.tap 88.tap 80.tap 90.tap \
    91.tap 92.tap 93.tap 94.tap 95.tap 96.tap 97.tap 98.tap 99.tap 100.tap \
    101.tap 102.tap 103.tap 104.tap 105.tap 106.tap 107.tap 108.tap 109.tap \
    110.tap 111.tap 112.tap 113.tap 114.tap 115.tap 116.tap 117.tap 118.tap \
    119.tap 120.tap 121.tap 122.tap 123.tap 124.tap 125.tap 126.tap 127.tap \
    128.tap 129.tap 130.tap 131.tap 132.tap 133.tap

clean:
	rm -f *.tap

.PHONY: all clean


01.tap:	01-color-attribute.asm
	$(ASSEMBLER) -v -d --tap $< $@ > 01-color-attribute.lst

02.tap:	02-blinking-attribute.asm
	$(ASSEMBLER) -v -d --tap $< $@ > 02-blinking-attribute.lst

03.tap:	03-symbolic-names.asm
	$(ASSEMBLER) -v -d --tap $< $@ > 03-symbolic-names.lst

04.tap:	04-operators.asm
	$(ASSEMBLER) -v -d --tap $< $@ > 04-operators.lst

05.tap:	05-better-symbols.asm
	$(ASSEMBLER) -v -d --tap $< $@ > 05-better-symbols.lst

06.tap:	06-tapbas-v1.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 06-tapbas-v1.lst

07.tap:	07-tapbas-v2.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 07-tapbas-v2.lst

08.tap:	08-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 08-loop.lst

09.tap:	09-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 09-loop.lst

10.tap:	10-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 10-loop.lst

11.tap:	11-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 11-loop.lst

12.tap:	12-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 12-loop.lst

13.tap:	13-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 13-loop.lst

14.tap:	14-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 14-loop.lst

15.tap:	15-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 15-loop.lst

16.tap:	16-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 16-loop.lst

17.tap:	17-loop.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 17-loop.lst

18.tap:	18-cls.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 18-cls.lst

19.tap:	19-print-char-call.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 19-print-char-call.lst

20.tap:	20-print-char-rst.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 20-print-char-rst.lst

21.tap:	21-print-char.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 21-print-char.lst

22.tap:	22-print-all-chars.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 22-print-all-chars.lst

23.tap:	23-print-all-chars.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 23-print-all-chars.lst

24.tap:	24-change-color.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 24-change-color.lst

25.tap:	25-change-flash.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 25-change-flash.lst

26.tap:	26-print-at.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 26-print-at.lst

27.tap:	27-print-string.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 27-print-string.lst

28.tap:	28-print-string.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 28-print-string.lst

29.tap:	29-print-colorized-string.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 29-print-colorized-string.lst

30.tap:	30-print-string-ROM.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 30-print-string-ROM.lst

31.tap:	31-attributes.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 31-attributes.lst

32.tap:	32-fill-in-vram.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 32-fill-in-vram.lst

33.tap:	33-fill-in-vram-no-ret.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 33-fill-in-vram-no-ret.lst

34.tap:	34-fill-in-vram-pattern.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 34-fill-in-vram-pattern.lst

35.tap:	35-slow-fill-in-vram.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 35-slow-fill-in-vram.lst

36.tap:	36-slow-fill-in-vram-no-ret.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 36-slow-fill-in-vram-no-ret.lst

37.tap:	37-fill-block.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 37-fill-block.lst

38.tap:	38-fill-block-with-pattern.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 38-fill-block-with-pattern.lst

39.tap:	39-fill-block-optimized.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 39-fill-block-optimized.lst

40.tap:	40-draw-char.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 40-draw-char.lst

41.tap:	41-draw-any-char.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 41-draw-any-char.lst

42.tap:	42-block-anywhere.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 42-block-anywhere.lst

43.tap:	43-block-anywhere-rrca.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 43-block-anywhere-rrca.lst

44.tap:	44-better-draw-char.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 44-better-draw-char.lst

45.tap:	45-even-better-draw-char.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 45-even-better-draw-char.lst

46.tap:	46-draw-char-at.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 46-draw-char-at.lst

47.tap:	47-draw-char-at-unrolled.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 47-draw-char-at-unrolled.lst

48.tap:	48-incorrect-print-string.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 48-incorrect-print-string.lst

49.tap:	49-correct-print-string.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 49-correct-print-string.lst

50.tap:	50-ascii-table.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 50-ascii-table.lst

51.tap:	51-plot-block.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 51-plot-block.lst

52.tap:	52-plot-pixel.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 52-plot-pixel.lst

53.tap:	53-plot-pixel.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 53-plot-pixel.lst

54.tap:	54-plot-pixel-on-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 54-plot-pixel-on-background.lst

55.tap:	55-plot-pixel-on-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 55-plot-pixel-on-background.lst

56.tap:	56-inverse-ascii-table.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 56-inverse-ascii-table.lst

57.tap:	57-plot-pixel-on-inverse-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 57-plot-pixel-on-inverse-background.lst

58.tap:	58-plot-inverse-pixel-on-inverse-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 58-plot-inverse-pixel-on-inverse-background.lst

59.tap:	59-configurable-ascii-table.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 59-configurable-ascii-table.lst

60.tap:	60-plot-over.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 60-plot-over.lst

61.tap:	61-print-number-A.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 61-print-number-A.lst

62.tap:	62-print-number-B.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 62-print-number-B.lst

63.tap:	63-print-number-C.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 63-print-number-C.lst

64.tap:	64-print-number-D.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 64-print-number-D.lst

65.tap:	65-more-numbers-A.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 65-more-numbers-A.lst

66.tap:	66-more-numbers-B.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 66-more-numbers-B.lst

67.tap:	67-print-flags-1.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 67-print-flags-1.lst

68.tap:	68-print-flags-2.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 68-print-flags-2.lst

69.tap:	69-print-flags-3.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 69-print-flags-3.lst

70.tap:	70-print-flags-4.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 70-print-flags-4.lst

71.tap:	71-print-flags-5.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 71-print-flags-5.lst

72.tap:	72-print-flags-6.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 72-print-flags-6.lst

73.tap:	73-print-flags-7.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 73-print-flags-7.lst

74.tap:	74-print-hex-number.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 74-print-hex-number.lst

75.tap:	75-print-hex-number.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 75-print-hex-number.lst

76.tap:	76-print-hex-numbers.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 76-print-hex-numbers.lst

77.tap:	77-add-hex-numbers.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 77-add-hex-numbers.lst

78.tap:	78-add-bcd-numbers.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 78-add-bcd-numbers.lst

79.tap:	79-print-hex-digit-jmp.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 79-print-hex-digit-jmp.lst

80.tap:	80-print-hex-digit-overflow.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 80-print-hex-digit-overflow.lst

81.tap:	81-print-hex-digit-daa.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 81-print-hex-digit-daa.lst

82.tap:	82-print-hex-numbers-daa.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 82-print-hex-numbers-daa.lst

83.tap:	83-print-fp-numbers.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 83-print-fp-numbers.lst

84.tap:	84-print-ascii-table.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 84-print-ascii-table.lst

85.tap:	85-copy-ascii-table.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 85-copy-ascii-table.lst

86.tap:	86-copy-ascii-table-B.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 86-copy-ascii-table-B.lst

87.tap:	87-copy-ascii-table-C.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 87-copy-ascii-table-C.lst

88.tap:	88-copy-ascii-table-D.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 88-copy-ascii-table-D.lst

89.tap:	89-copy-ascii-table-E.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 89-copy-ascii-table-E.lst

90.tap:	90-copy-ascii-table-F.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 90-copy-ascii-table-F.lst

91.tap:	91-copy-ascii-table-G.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 91-copy-ascii-table-G.lst

92.tap:	92-copy-ascii-table-H.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 92-copy-ascii-table-H.lst

93.tap:	93-copy-ascii-table-I.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 93-copy-ascii-table-I.lst

94.tap:	94-color-attribute.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 94-color-attribute.lst

95.tap:	95-keypress.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 95-keypress.lst

96.tap:	96-keypress-row.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 96-keypress-row.lst

97.tap:	97-keypress-all-rows.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 97-keypress-all-rows.lst

98.tap:	98-game-character.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 98-game-character.lst

99.tap:	99-game-character-2.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 99-game-character-2.lst

100.tap:	100-cursor-joystick.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 100-cursor-joystick.lst

101.tap:	101-sinclair-joystick.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 101-sinclair-joystick.lst

102.tap:	102-kempston-joystick.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 102-kempston-joystick.lst

103.tap:	103-beep.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 103-beep.lst

104.tap:	104-music-scale.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 104-music-scale.lst

105.tap:	105-direct-speaker.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 105-direct-speaker.lst

106.tap:	106-direct-speaker-di.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 106-direct-speaker-di.lst

107.tap:	107-direct-speaker-border.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 107-direct-speaker-border.lst

108.tap:	108-direct-speaker-border-di.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 108-direct-speaker-border-di.lst

109.tap:	109-ay-note-a.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 109-ay-note-a.lst

110.tap:	110-ay-note-a.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 110-ay-note-a.lst

111.tap:	111-ay-two-notes.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 111-ay-two-notes.lst

112.tap:	112-ay-noise.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 112-ay-noise.lst

113.tap:	113-ay-low-frequency.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 113-ay-low-frequency.lst

114.tap:	114-ay-high-frequency.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 114-ay-high-frequency.lst

115.tap:	115-ay-low-noise.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 115-ay-low-noise.lst

116.tap:	116-ay-envelope.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 116-ay-envelope.lst

117.tap:	117-ay-envelope.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 117-ay-envelope.lst

118.tap:	118-ay-envelope.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 118-ay-envelope.lst

119.tap:	119-noise-envelope.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 119-noise-envelope.lst

120.tap:	120-8x8-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 120-8x8-sprite.lst

121.tap:	121-24x24-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 121-24x24-sprite.lst

122.tap:	122-24x24-sprite.asm sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 122-24x24-sprite.lst

123.tap:	123-24x24-sprite.asm sprite.bin
	$(ASSEMBLER) -v -d --tapbas $< $@ > 123-24x24-sprite.lst

124.tap:	124-shifted-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 124-shifted-sprite.lst

125.tap:	125-shifted-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 125-shifted-sprite.lst

126.tap:	126-24x24-faster-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 126-24x24-faster-sprite.lst

127.tap:	127-margins.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 127-margins.lst

128.tap:	128-margins.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 128-margins.lst

129.tap:	129-screen-addressing.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 129-screen-addressing.lst

130.tap:	130-screen-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 130-screen-background.lst

131.tap:	131-screen-background-and-sprite.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 131-screen-background-and-sprite.lst

132.tap:	132-improper-sprite-addressing.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 132-improper-sprite-addressing.lst

133.tap:	133-proper-sprite-addressing.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 133-proper-sprite-addressing.lst

134.tap:	134-copy-sprite-in-sw.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 134-copy-sprite-in-sw.lst

135.tap:	135-shift-sprite-in-sw.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 135-shift-sprite-in-sw.lst

136.tap:	136-shift-sprite-in-sw.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 136-shift-sprite-in-sw.lst

137.tap:	137-on-background.asm
	$(ASSEMBLER) -v -d --tapbas $< $@ > 137-on-background.lst
